services:
  seed4j:
    image: seed4j/seed4j:main
    container_name: seed4j
    environment:
      APPLICATION_CORS_ALLOWED_ORIGINS: https://start.seed4j.com
      SEED4J_FORCED_PROJECT_FOLDER: /tmp/seed4j
    expose:
      - '1339'
    volumes:
      - ./tmp:/tmp/seed4j:Z

  nginx:
    image: nginx:1.29
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./certs/seed4j.crt:/etc/ssl/certs/seed4j.crt:ro
      - ./certs/seed4j.key:/etc/ssl/private/seed4j.key:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - seed4j
